### ISSUE TITLE
GridFieldOrderableRows doesn't work when used for related data objects of an unsaved parent data object

### ISSUE THREAD

**Issue by filiplikavcan** [symbiote/silverstripe-gridfieldextensions#98]
This commit https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/commit/4015d3355f2826fe3a754acdd3138523681cb3c3 changes $sortterm passed to ArrayList#sort method which assumes that only column name is quoted not the table name. See here: https://github.com/silverstripe/silverstripe-framework/blob/3.2/model/ArrayList.php#L363

When a data object class 'Parent' has a has_many relation with data object class 'Child' named 'Children' and I want to create new 'Parent' data object it raises exception and doesn't show 'Parent' form.

When I override Children method on 'Parent' class like this it works but it is a workaround I don't like:

```
public function Children()
{
    if (empty($this->ID))
    {
        return Child::get()->filter(array('ParentID' => $this->ID))->sort('SortOrder');
    }
    else
    {
        return parent::Children();
    }
}
```

**Comment by filiplikavcan** [comment]
It is probably because Children method returns ArrayList instead of DataList when Parent is not saved. ArrayList sort method calls parseSortColumn method which causes this problem.

**Comment by nyeholt** [comment]
I've just pushed up a branch that has a possible fix (ie detects if there's an arraylist or data list being used) - are you able to try that out?

**Comment by ss23** [comment]
Believe I'm hitting this same issue (manifests as `Couldn't find the sort field 'Sort'`), and that branch does not fix the issue, @nyeholt

**Comment by nyeholt** [comment]
So the updated issue title is slightly different to the original issue - in the situation of an unsaved object having a gridfield, it can't figure out how to do the re-ordering because the list being operated on (at that point in time) is an unsavedrelationlist, not a manymany/hasmany list. The workaround is to only add the sortable options for the gridfield after the parent option has an ID

**Comment by nickspiel** [comment]
I have come across a very similar issue: http://stackoverflow.com/questions/33075844/silverstripe-gridfield-multi-class-editor-has-invalid-sort-column

**Comment by nickspiel** [comment]
I came up with a different workaround.

```
$textBlocks = GridField::create('TextBlocks', 'Text Blocks', $this-> TextBlocks(), 
	GridFieldConfig::create()->addComponents(
		new GridFieldToolbarHeader(),
		new GridFieldAddNewButton('toolbar-header-right'),
		new GridFieldDetailForm(),
		new GridFieldDataColumns(),
		new GridFieldEditButton(),
		new GridFieldDeleteAction('unlinkrelation'),
		new GridFieldDeleteAction(),
		new GridFieldTitleHeader(),
		new GridFieldAddExistingAutocompleter('before', array('Title')) // Link existing
	)
);

// Add the OrderableRows component if the parent object has an ID
if($this->ID) {
    $textBlocks->addComponents(
        new GridFieldOrderableRows('SortOrder')
    );
}
```

**Comment by nyeholt** [comment]
Yep, that's the recommended approach - list sorting won't work until the parent has an ID (and the subsequent data list exists).

**Comment by michalkleiner** [comment]
Was this issue resolved? Or is the recommended solution to add the OrderableRows component only when the list is saved? Either way it'd be good to close this to clean the list up a bit.

**Comment by robbieaverill** [comment]
This situation occurs occasionally with various SS components - best to check the object/parent exists before adding components that control children of it if it's not in the DB yet.
